Repository 202-ecommerce/stripe_official, pull requests merged in 2020-06, with the labels that each got.

#3 allows overriding the controller names for which the stripe headers a…
  stripe_official.php
Labels: enhancement

#21 fix errors in classes/actions/ValidationOrderActions.php
  classes/actions/ValidationOrderActions.php
Labels: bug

#23 CO: Remove unnecessary call to Module::getInstanceByName
  classes/StripeWebhook.php
Labels: Refactoring
